# Generated by Django 2.2.5 on 2019-09-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('realeased', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('rated', models.CharField(max_length=10)),
                ('plot', models.CharField(max_length=1000)),
            ],
        ),
    ]
